[package]
name = "year2016"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "q1"
path = "src/q1.rs"

[[bin]]
name = "q2"
path = "src/q2.rs"

[[bin]]
name = "q3"
path = "src/q3.rs"

[dependencies]
flamegraph = "0.6.5"

[profile.dev]
opt-level = 3
debug = true

[profile.release]
opt-level = 3
debug = true
