CPPFLAGS=-Wall -Wextra -pg -g

all: q1a q1b q3a q3b

q1a: q1.h q1.cc q1a.cc
	g++ q1.cc q1a.cc -o q1a $(CPPFLAGS)

q1b: q1.h q1.cc q1b.cc
	g++ q1.cc q1b.cc -o q1b $(CPPFLAGS)

q3a: q3.h q3.cc q3a.cc
	g++ q3.cc q3a.cc -o q3a $(CPPFLAGS)

q3b: q3.h q3.cc q3b.cc
	g++ q3.cc q3b.cc -o q3b $(CPPFLAGS)
