CFLAGS=-Wall -Wextra 

all: q1a q3a

clean:
	rm -f q1a q3a

q1a: q1.c q1a.c q1.h
	gcc q1.c q1a.c -o q1a $(CFLAGS)

q2a: q2.cc q2a.cc q2.h
	g++ q2.cc q2a.cc -o q2a $(CFLAGS)

q3a: q3.cc q3a.cc q3.h
	g++ q3.cc q3a.cc -o q3a $(CFLAGS)
